"""FastAPI reference workload for the Hybrid Observability Platform."""

import asyncio
from collections.abc import AsyncIterator
from contextlib import asynccontextmanager
from time import perf_counter
from typing import Annotated, Literal

from fastapi import FastAPI, Path, Query, Request
from fastapi.responses import JSONResponse
from opentelemetry import trace
from opentelemetry.trace import Status, StatusCode
from pydantic import BaseModel

from hybrid_observability.config import Settings, get_settings
from hybrid_observability.logging import configure_logging, get_logger
from hybrid_observability.telemetry import TelemetryRuntime, initialize_telemetry

logger = get_logger(__name__)

DependencyOutcome = Literal["success", "failure", "timeout"]


class HealthResponse(BaseModel):
    """Health-check response."""

    status: str
    service: str
    version: str
    environment: str
    telemetry_enabled: bool


class ItemResponse(BaseModel):
    """Example business response."""

    item_id: int
    name: str
    status: str


class ScenarioResponse(BaseModel):
    """Controlled observability scenario response."""

    scenario: str
    outcome: str
    duration_ms: int | None = None


class ErrorResponse(BaseModel):
    """Standard error response."""

    error: str
    message: str
    trace_id: str | None = None


class ControlledScenarioError(Exception):
    """Expected failure generated by an observability scenario."""

    def __init__(
        self,
        *,
        error: str,
        message: str,
        status_code: int,
    ) -> None:
        super().__init__(message)
        self.error = error
        self.message = message
        self.status_code = status_code


def _current_trace_id() -> str | None:
    """Return the active OpenTelemetry trace identifier."""

    span_context = trace.get_current_span().get_span_context()

    if not span_context.is_valid:
        return None

    return format(span_context.trace_id, "032x")


async def _simulate_dependency_call(
    outcome: DependencyOutcome,
    timeout_seconds: float,
) -> None:
    """Simulate a bounded call to an external dependency."""

    if outcome == "success":
        await asyncio.sleep(0.05)
        return

    if outcome == "failure":
        await asyncio.sleep(0.05)
        raise ConnectionError("Simulated dependency connection failure")

    await asyncio.wait_for(
        asyncio.sleep(timeout_seconds + 0.1),
        timeout=timeout_seconds,
    )


def create_app(settings: Settings | None = None) -> FastAPI:
    """Create and configure one FastAPI application instance."""

    resolved_settings = settings or get_settings()
    configure_logging(resolved_settings)

    telemetry_runtime: TelemetryRuntime | None = None

    @asynccontextmanager
    async def lifespan(application: FastAPI) -> AsyncIterator[None]:
        logger.info(
            "application_started",
            extra={
                "host": resolved_settings.host,
                "port": resolved_settings.port,
            },
        )

        yield

        logger.info("application_stopping")

        if telemetry_runtime is not None:
            telemetry_runtime.shutdown()

    application = FastAPI(
        title="Hybrid Observability API",
        description=(
            "Instrumented reference workload for metrics, logs, traces, "
            "and controlled failure scenarios."
        ),
        version=resolved_settings.service_version,
        lifespan=lifespan,
    )

    telemetry_runtime = initialize_telemetry(
        application,
        resolved_settings,
    )

    scenario_requests = telemetry_runtime.meter.create_counter(
        "app.scenario.requests",
        unit="{request}",
        description="Number of controlled observability scenario requests.",
    )
    scenario_duration = telemetry_runtime.meter.create_histogram(
        "app.scenario.duration",
        unit="ms",
        description="Duration of controlled observability scenarios.",
    )
    dependency_requests = telemetry_runtime.meter.create_counter(
        "app.dependency.requests",
        unit="{request}",
        description="Number of simulated dependency requests.",
    )
    dependency_duration = telemetry_runtime.meter.create_histogram(
        "app.dependency.duration",
        unit="ms",
        description="Duration of simulated dependency requests.",
    )

    application.state.settings = resolved_settings
    application.state.telemetry = telemetry_runtime

    @application.exception_handler(ControlledScenarioError)
    async def controlled_scenario_error_handler(
        request: Request,
        exception: ControlledScenarioError,
    ) -> JSONResponse:
        trace_id = _current_trace_id()

        logger.warning(
            "controlled_scenario_failed",
            extra={
                "error": exception.error,
                "path": request.url.path,
                "status_code": exception.status_code,
            },
        )

        response = ErrorResponse(
            error=exception.error,
            message=exception.message,
            trace_id=trace_id,
        )

        return JSONResponse(
            status_code=exception.status_code,
            content=response.model_dump(),
        )

    @application.get(
        "/health/live",
        response_model=HealthResponse,
        tags=["health"],
    )
    async def liveness() -> HealthResponse:
        """Confirm that the application process is running."""

        return HealthResponse(
            status="alive",
            service=resolved_settings.service_name,
            version=resolved_settings.service_version,
            environment=resolved_settings.deployment_environment,
            telemetry_enabled=resolved_settings.telemetry_enabled,
        )

    @application.get(
        "/health/ready",
        response_model=HealthResponse,
        tags=["health"],
    )
    async def readiness() -> HealthResponse:
        """Confirm that the application is ready to receive requests."""

        return HealthResponse(
            status="ready",
            service=resolved_settings.service_name,
            version=resolved_settings.service_version,
            environment=resolved_settings.deployment_environment,
            telemetry_enabled=resolved_settings.telemetry_enabled,
        )

    @application.get(
        "/api/v1/items/{item_id}",
        response_model=ItemResponse,
        tags=["items"],
    )
    async def get_item(
        item_id: Annotated[int, Path(ge=1)],
    ) -> ItemResponse:
        """Return a deterministic reference item."""

        logger.info(
            "item_retrieved",
            extra={"item_id": item_id},
        )

        return ItemResponse(
            item_id=item_id,
            name=f"reference-item-{item_id}",
            status="available",
        )

    @application.get(
        "/api/v1/scenarios/latency",
        response_model=ScenarioResponse,
        tags=["scenarios"],
    )
    async def latency_scenario(
        delay_ms: Annotated[int, Query(ge=0)] = 250,
    ) -> ScenarioResponse:
        """Introduce a bounded and observable response delay."""

        if delay_ms > resolved_settings.maximum_scenario_delay_ms:
            scenario_requests.add(
                1,
                {
                    "scenario.type": "latency",
                    "scenario.outcome": "rejected",
                },
            )
            raise ControlledScenarioError(
                error="scenario_delay_exceeded",
                message=(
                    "Requested delay exceeds the configured maximum "
                    f"of {resolved_settings.maximum_scenario_delay_ms} ms."
                ),
                status_code=400,
            )

        with telemetry_runtime.tracer.start_as_current_span("scenario.latency") as span:
            span.set_attribute("scenario.type", "latency")
            span.set_attribute("scenario.delay_ms", delay_ms)

            logger.info(
                "latency_scenario_started",
                extra={"delay_ms": delay_ms},
            )

            await asyncio.sleep(delay_ms / 1000)

            logger.info(
                "latency_scenario_completed",
                extra={"delay_ms": delay_ms},
            )

        scenario_requests.add(
            1,
            {
                "scenario.type": "latency",
                "scenario.outcome": "success",
            },
        )
        scenario_duration.record(
            delay_ms,
            {"scenario.type": "latency"},
        )

        return ScenarioResponse(
            scenario="latency",
            outcome="success",
            duration_ms=delay_ms,
        )

    @application.get(
        "/api/v1/scenarios/error",
        response_model=ScenarioResponse,
        responses={503: {"model": ErrorResponse}},
        tags=["scenarios"],
    )
    async def error_scenario() -> ScenarioResponse:
        """Generate a controlled service error."""

        logger.warning("error_scenario_triggered")

        scenario_requests.add(
            1,
            {
                "scenario.type": "error",
                "scenario.outcome": "failure",
            },
        )

        raise ControlledScenarioError(
            error="controlled_service_failure",
            message="A controlled service failure was generated.",
            status_code=503,
        )

    @application.get(
        "/api/v1/scenarios/dependency",
        response_model=ScenarioResponse,
        responses={
            502: {"model": ErrorResponse},
            504: {"model": ErrorResponse},
        },
        tags=["scenarios"],
    )
    async def dependency_scenario(
        outcome: Annotated[DependencyOutcome, Query()] = "success",
    ) -> ScenarioResponse:
        """Simulate success, failure, or timeout from a dependency."""

        started_at = perf_counter()

        try:
            with telemetry_runtime.tracer.start_as_current_span("dependency.simulated") as span:
                span.set_attribute("dependency.name", "simulated-upstream")
                span.set_attribute("dependency.outcome", outcome)

                await _simulate_dependency_call(
                    outcome,
                    resolved_settings.dependency_timeout_seconds,
                )

                span.set_status(Status(StatusCode.OK))

        except TimeoutError as exception:
            duration_ms = (perf_counter() - started_at) * 1000
            dependency_requests.add(1, {"dependency.outcome": "timeout"})
            dependency_duration.record(
                duration_ms,
                {"dependency.outcome": "timeout"},
            )
            logger.warning(
                "dependency_timeout",
                extra={"dependency": "simulated-upstream"},
            )

            raise ControlledScenarioError(
                error="dependency_timeout",
                message="The simulated dependency exceeded its timeout.",
                status_code=504,
            ) from exception

        except ConnectionError as exception:
            duration_ms = (perf_counter() - started_at) * 1000
            dependency_requests.add(1, {"dependency.outcome": "failure"})
            dependency_duration.record(
                duration_ms,
                {"dependency.outcome": "failure"},
            )
            logger.warning(
                "dependency_failure",
                extra={"dependency": "simulated-upstream"},
            )

            raise ControlledScenarioError(
                error="dependency_unavailable",
                message="The simulated dependency is unavailable.",
                status_code=502,
            ) from exception

        duration_ms = (perf_counter() - started_at) * 1000
        dependency_requests.add(1, {"dependency.outcome": "success"})
        dependency_duration.record(
            duration_ms,
            {"dependency.outcome": "success"},
        )

        logger.info(
            "dependency_call_completed",
            extra={
                "dependency": "simulated-upstream",
                "outcome": outcome,
            },
        )

        return ScenarioResponse(
            scenario="dependency",
            outcome="success",
        )

    return application


app = create_app()
